### PR TITLE
Add step to make sure CSRF protection is disabled for version 5.6.2 a…

### PR DESCRIPTION
**Pull request by kayzhebb**

### CODE REVIEW

**Comment by kayzhebb** [comment]
According to Niels, in 5.6.3, you can keep the CSRF enabled. For Mobile (Log in with the SDK), it will ignore this validation. So that's why I put below.

I will add the full instruction for disabling for the next pull request.

**Comment by kayzhebb** [comment]
Can you let me know if the instructions are ok?

**Comment by dragoverde** [comment]
Ok, but CXRF protection has only been introduced in 5.6.2. In that case, just get rid of the "and below" fragment.

**Comment by kayzhebb** [comment]
Ok, then I'll remove it 👍

**Pull request merged**
